### ISSUE TITLE
Login method not working (Open to fixes)

### ISSUE THREAD

**Issue by phytal** [Phytal/HomeAccessCenter-Web-API#1]
It seems there is an Internal Error 500 when trying to log in to HAC. As this method worked before, it could because of a change in how HAC handles logins. I've tried many combinations of headers in the HttpClient, however none of them works. It may be time for a migration unless there is a possible fix.

**Comment by lucasheer** [comment]
Not sure if this is still needed!

I remember there was a token generated when you started up the main /login page. It is required that you put this in the POST login request.

Looking to get back into this to develop a robust API! I love the one you have built!

Also, could you add me on discord? Lucasheer#3361

Thank you!

**Comment by phytal** [comment]
It turned out that the token was the issue! Now there are so many new issues since its been 2 years since I worked on this code. I'll push the fixed code soon~ Thanks for your help!

I'd love to add you on Discord but your tag is invalid, add me on Phytal#8213
